### ISSUE TITLE
tag new release

### ISSUE THREAD

**Issue by colemickens** [spectare/fakeidp#372]
The Cargo.lock on 1.0.0 is not locked correctly. Thus I can't package it for Nixpkgs.

**Comment by colemickens** [comment]
Well, this might not be accurate. Not sure, I bumped to latest on main.

**Comment by olger** [comment]
Hi @colemickens when something is wrong in some kind of way, I am happy to fix it, just drop a message (or issue) when required.

**Comment by colemickens** [comment]
Thanks for such a nice message. So far, things are great. I have a generic OIDC client and it happily uses discovery, fetches keys, validates a token I got from fakeidp. Works great! And lovely to replace a ... similar, less functional nodejs tool.
